CREATE TABLE IF NOT EXISTS IMAGE (
    ID BIGINT AUTO_INCREMENT,
    DESCRIPTION VARCHAR(100),
    IMAGE BLOB,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS OBJET_A_COLLECTIONNER (
    ID BIGINT AUTO_INCREMENT,
    CODE VARCHAR(100),
    RARETE VARCHAR(2),
    IMAGE_ID BIGINT,
    PRIMARY KEY (ID),
    CONSTRAINT fk_objet_collection_image FOREIGN KEY (IMAGE_ID) REFERENCES IMAGE(ID)
);